// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39KQXiCE2dUY8au4KThqJ2ozSTKlkfEQ',
    appId: '1:469298655595:web:1c618b344ee40734945c2e',
    messagingSenderId: '469298655595',
    projectId: 'familycalendar-a960a',
    authDomain: 'familycalendar-a960a.firebaseapp.com',
    storageBucket: 'familycalendar-a960a.firebasestorage.app',
    measurementId: 'G-3RPD6Y7ZGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7GvojLOdO-_DFQTrjbynFZzb9Rp8Hcs',
    appId: '1:469298655595:android:ef14a7f3d80dfc1e945c2e',
    messagingSenderId: '469298655595',
    projectId: 'familycalendar-a960a',
    storageBucket: 'familycalendar-a960a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HDzvrYkA6vi82DokobdaMoXjHzXAfZY',
    appId: '1:469298655595:ios:a0aa66f48ced3b71945c2e',
    messagingSenderId: '469298655595',
    projectId: 'familycalendar-a960a',
    storageBucket: 'familycalendar-a960a.firebasestorage.app',
    iosBundleId: 'com.example.familycalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HDzvrYkA6vi82DokobdaMoXjHzXAfZY',
    appId: '1:469298655595:ios:a0aa66f48ced3b71945c2e',
    messagingSenderId: '469298655595',
    projectId: 'familycalendar-a960a',
    storageBucket: 'familycalendar-a960a.firebasestorage.app',
    iosBundleId: 'com.example.familycalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA39KQXiCE2dUY8au4KThqJ2ozSTKlkfEQ',
    appId: '1:469298655595:web:772a7edfaab15eab945c2e',
    messagingSenderId: '469298655595',
    projectId: 'familycalendar-a960a',
    authDomain: 'familycalendar-a960a.firebaseapp.com',
    storageBucket: 'familycalendar-a960a.firebasestorage.app',
    measurementId: 'G-1D30HFLZF3',
  );
}
